<a href="https://colab.research.google.com/github/asaadkhan21/Machine-Learning-Lab/blob/main/Lab_1_DataPreprocessing_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_set=pd.read_csv('dataset.csv')
data_set.head(5)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [4]:
data_set.shape


(10, 4)

In [5]:
data_set.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
X=data_set.iloc[:,:-1].values
y=data_set.iloc[:,3].values
print(X)
y

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [7]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='median')
imputer=imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x=LabelEncoder()
X[:,0]=label_encoder_x.fit_transform(X[:,0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 61000.0],
       [0, 35.0, 58000.0],
       [2, 38.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [9]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columntransfomer=ColumnTransformer([('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X=np.array(columntransfomer.fit_transform(X),dtype=np.str)
X

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


array([['1.0', '0.0', '0.0', '44.0', '72000.0'],
       ['0.0', '0.0', '1.0', '27.0', '48000.0'],
       ['0.0', '1.0', '0.0', '30.0', '54000.0'],
       ['0.0', '0.0', '1.0', '38.0', '61000.0'],
       ['0.0', '1.0', '0.0', '40.0', '61000.0'],
       ['1.0', '0.0', '0.0', '35.0', '58000.0'],
       ['0.0', '0.0', '1.0', '38.0', '52000.0'],
       ['1.0', '0.0', '0.0', '48.0', '79000.0'],
       ['0.0', '1.0', '0.0', '50.0', '83000.0'],
       ['1.0', '0.0', '0.0', '37.0', '67000.0']], dtype='<U7')

In [10]:
labelencoder_y= LabelEncoder()  
y= labelencoder_y.fit_transform(y) 
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)
X_test

array([['0.0', '1.0', '0.0', '30.0', '54000.0'],
       ['0.0', '1.0', '0.0', '50.0', '83000.0']], dtype='<U7')

In [12]:
from sklearn.preprocessing import StandardScaler  
st_x= StandardScaler()  
X_train= st_x.fit_transform(X_train)  

print(X_train)

X_test= st_x.transform(X_test)  
print(X_test)

[[-1.          2.64575131 -0.77459667  0.27978024 -0.13108063]
 [ 1.         -0.37796447 -0.77459667 -0.23673712  0.49810638]
 [-1.         -0.37796447  1.29099445 -1.95846165 -1.49431914]
 [-1.         -0.37796447  1.29099445 -0.06456467 -1.07486114]
 [ 1.         -0.37796447 -0.77459667  1.65715986  1.75648039]
 [-1.         -0.37796447  1.29099445 -0.06456467 -0.13108063]
 [ 1.         -0.37796447 -0.77459667  0.96847005  1.02242888]
 [ 1.         -0.37796447 -0.77459667 -0.58108203 -0.44567413]]
[[-1.          2.64575131 -0.77459667 -1.44194429 -0.86513213]
 [-1.          2.64575131 -0.77459667  2.00150476  2.1759384 ]]
